export {default as Basic} from '../Tabs/Basic/Basic'
export {default as Education} from '../Tabs/Education/Education'
export {default as Work} from '../Tabs/Work/Work'
export {default as Skill} from '../Tabs/Skill/Skill'
export {default as Award} from '../Tabs/Awards/Award'